spring:
  datasource:
#    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
#    username: ${MYSQLUSER}
#    password: ${MYSQLPASSWORD}
    url: jdbc:${MYSQL_PUBLIC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL8Dialect



#spring:
#  datasource:
#    #    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
#    url: jdbc:mysql://root:fIZeGetXeVdQPXUOmkMsPMZoOMERhsKy@metro.proxy.rlwy.net:16753/railway
#    username: ${MYSQLUSER}
#    password: ${MYSQLPASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: validate
#      dialect: org.hibernate.dialect.MySQL8Dialect

task.jar{
manifest{
attributes["Main-Class] = "HealthSafe.HealthSafeApplication"