spring:
  datasource:
    url: jdbc:h2:mem:healthsafe
    username: sa
    password: sa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console  #http://localhost:8080/h2-console
      settings:
        trace: false
        web-allow-others: false
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
